version: '3'
services:
    redis:
        image: redis:latest
        hostname: redis
        ports:
            - 6379:6379
        restart: always
        healthcheck:
            test: redis-cli ping
            interval: 60s
            timeout: 10s
            retries: 5
    rabbitmq:
        image: rabbitmq:management
        hostname: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        healthcheck:
            test: rabbitmqctl status
            interval: 60s
            timeout: 10s
            retries: 5
    beat:
        image: myflask
        build:
            context: ./flask
            dockerfile: Dockerfile
        depends_on:
            - worker
        command: bash beat.sh
        healthcheck:
            test: kill -0 $$(cat /opt/celeryworker.pid)
            interval: 30s
            timeout: 10s
            retries: 3
    flask:
        image: myflask
        build:
            context: ./flask
            dockerfile: Dockerfile
        depends_on:
            - redis
            - rabbitmq
        restart: always
        command: bash flask.sh
        ports:
            - 5000:5000
        healthcheck:
            test: curl -f http://localhost:5000/ping || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
    worker:
        image: myflask
        build:
            context: ./flask
            dockerfile: Dockerfile
        depends_on:
            - redis
            - rabbitmq
        restart: always
        command: bash worker.sh
        healthcheck:
            test: kill -0 $$(cat /opt/celeryworker.pid)
            interval: 30s
            timeout: 10s
            retries: 0
